##data cleaning

In [101]:
import pandas as pd
import numpy as np

# 加载数据
file_path = r"C:\Users\ronny\Desktop\美赛\raw\2026_MCM_Problem_C_Data.csv"
data = pd.read_csv(file_path)

# 查看数据的基本信息和前几行，确保加载成功
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421 entries, 0 to 420
Data columns (total 53 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   celebrity_name                421 non-null    object
 1   ballroom_partner              421 non-null    object
 2   celebrity_industry            421 non-null    object
 3   celebrity_homestate           365 non-null    object
 4   celebrity_homecountry/region  421 non-null    object
 5   celebrity_age_during_season   421 non-null    int64
 6   season                        421 non-null    int64
 7   results                       421 non-null    object
 8   placement                     421 non-null    int64
 9   week1_judge1_score            421 non-null    float64
 10  week1_judge2_score            421 non-null    float64
 11  week1_judge3_score            407 non-null    float64
 12  week1_judge4_score            81 non-null     float64
 13  week2_judge1_score            421 non-null    float64
 14  week2_judge2_score            421 non-null    float64
 15  week2_judge3_score            421 non-null    float64
 16  week2_judge4_score            91 non-null     float64
 17  week3_judge1_score            421 non-null    float64
 18  week3_judge2_score            421 non-null    float64
 19  week3_judge3_score            421 non-null    float64
 20  week3_judge4_score            128 non-null    float64
 21  week4_judge1_score            421 non-null    float64
 22  week4_judge2_score            421 non-null    float64
 23  week4_judge3_score            421 non-null    float64
 24  week4_judge4_score            130 non-null    float64
 25  week5_judge1_score            411 non-null    float64
 26  week5_judge2_score            411 non-null    float64
 27  week5_judge3_score            411 non-null    float64
 28  week5_judge4_score            119 non-null    float64
 29  week6_judge1_score            411 non-null    float64
 30  week6_judge2_score            411 non-null    float64
 31  week6_judge3_score            411 non-null    float64
 32  week6_judge4_score            147 non-null    float64
 33  week7_judge1_score            405 non-null    float64
 34  week7_judge2_score            405 non-null    float64
 35  week7_judge3_score            405 non-null    float64
 36  week7_judge4_score            144 non-null    float64
 37  week8_judge1_score            405 non-null    float64
 38  week8_judge2_score            405 non-null    float64
 39  week8_judge3_score            405 non-null    float64
 40  week8_judge4_score            108 non-null    float64
 41  week9_judge1_score            395 non-null    float64
 42  week9_judge2_score            395 non-null    float64
 43  week9_judge3_score            395 non-null    float64
 44  week9_judge4_score            133 non-null    float64
 45  week10_judge1_score           369 non-null    float64
 46  week10_judge2_score           369 non-null    float64
 47  week10_judge3_score           369 non-null    float64
 48  week10_judge4_score           93 non-null     float64
 49  week11_judge1_score           119 non-null    float64
 50  week11_judge2_score           119 non-null    float64
 51  week11_judge3_score           119 non-null    float64
 52  week11_judge4_score           26 non-null     float64
dtypes: float64(44), int64(3), object(6)
memory usage: 174.4+ KB

,celebrity_name,ballroom_partner,celebrity_industry,celebrity_homestate,celebrity_homecountry/region,celebrity_age_during_season,season,results,placement,week1_judge1_score,...,week9_judge3_score,week9_judge4_score,week10_judge1_score,week10_judge2_score,week10_judge3_score,week10_judge4_score,week11_judge1_score,week11_judge2_score,week11_judge3_score,week11_judge4_score
0,John O'Hurley,Charlotte Jorgensen,Actor/Actress,Maine,United States,50,1,2nd Place,2,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Kelly Monaco,Alec Mazo,Actor/Actress,Pennsylvania,United States,29,1,1st Place,1,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Evander Holyfield,Edyta Sliwinska,Athlete,Alabama,United States,42,1,Eliminated Week 3,5,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Rachel Hunter,Jonathan Roberts,Model,NaN,New Zealand,35,1,Eliminated Week 4,4,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Joey McIntyre,Ashly DelGrosso,Singer/Rapper,Massachusetts,United States,32,1,3rd Place,3,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [103]:
# 检查每一列中的缺失值数量
missing_data = data.isna().sum()

# 输出缺失值数量
print("缺失值数量：")
print(missing_data)

缺失值数量：
celebrity_name                    0
ballroom_partner                  0
celebrity_industry                0
celebrity_homestate              56
celebrity_homecountry/region      0
celebrity_age_during_season       0
season                            0
results                           0
placement                         0
week1_judge1_score                0
week1_judge2_score                0
week1_judge3_score               14
week1_judge4_score              340
week2_judge1_score                0
week2_judge2_score                0
week2_judge3_score                0
week2_judge4_score              330
week3_judge1_score                0
week3_judge2_score                0
week3_judge3_score                0
week3_judge4_score              293
week4_judge1_score                0
week4_judge2_score                0
week4_judge3_score                0
week4_judge4_score              291
week5_judge1_score               10
week5_judge2_score               10
week5_judge3_score               10
week5_judge4_score              302
week6_judge1_score               10
week6_judge2_score               10
week6_judge3_score               10
week6_judge4_score              274
week7_judge1_score               16
week7_judge2_score               16
week7_judge3_score               16
week7_judge4_score              277
week8_judge1_score               16
week8_judge2_score               16
week8_judge3_score               16
week8_judge4_score              313
week9_judge1_score               26
week9_judge2_score               26
week9_judge3_score               26
week9_judge4_score              288
week10_judge1_score              52
week10_judge2_score              52
week10_judge3_score              52
week10_judge4_score             328
week11_judge1_score             302
week11_judge2_score             302
week11_judge3_score             302
week11_judge4_score             395
dtype: int64

In [105]:
# 对 `week_X_judge_Y_score` 类型的列进行填补，填充为 NaN
for col in data.columns:
    if 'week' in col and 'judge' in col:  # 针对评委评分列
        data[col] = data[col].where(data[col].notna(), np.nan)  # 将缺失值保留为NaN

# 检查填补后的缺失值
missing_data_after = data.isna().sum()
print("填补后的缺失值数量：")
print(missing_data_after)

填补后的缺失值数量：
celebrity_name                    0
ballroom_partner                  0
celebrity_industry                0
celebrity_homestate              56
celebrity_homecountry/region      0
celebrity_age_during_season       0
season                            0
results                           0
placement                         0
week1_judge1_score                0
week1_judge2_score                0
week1_judge3_score               14
week1_judge4_score              340
week2_judge1_score                0
week2_judge2_score                0
week2_judge3_score                0
week2_judge4_score              330
week3_judge1_score                0
week3_judge2_score                0
week3_judge3_score                0
week3_judge4_score              293
week4_judge1_score                0
week4_judge2_score                0
week4_judge3_score                0
week4_judge4_score              291
week5_judge1_score               10
week5_judge2_score               10
week5_judge3_score               10
week5_judge4_score              302
week6_judge1_score               10
week6_judge2_score               10
week6_judge3_score               10
week6_judge4_score              274
week7_judge1_score               16
week7_judge2_score               16
week7_judge3_score               16
week7_judge4_score              277
week8_judge1_score               16
week8_judge2_score               16
week8_judge3_score               16
week8_judge4_score              313
week9_judge1_score               26
week9_judge2_score               26
week9_judge3_score               26
week9_judge4_score              288
week10_judge1_score              52
week10_judge2_score              52
week10_judge3_score              52
week10_judge4_score             328
week11_judge1_score             302
week11_judge2_score             302
week11_judge3_score             302
week11_judge4_score             395
dtype: int64

In [107]:
# 创建新的列 `celebrity_homeland`
def create_homeland(row):
    if row['celebrity_homecountry/region'] == 'United States' and pd.notna(row['celebrity_homestate']):
        return row['celebrity_homestate']  # 如果来自美国，取 `celebrity_homestate`
    else:
        return row['celebrity_homecountry/region']  # 否则取 `celebrity_homecountry/region`

# 应用函数合并 `celebrity_homestate` 和 `celebrity_homecountry/region`
data['celebrity_homeland'] = data.apply(create_homeland, axis=1)

# 删除 `celebrity_homestate` 和 `celebrity_homecountry/region` 列（如果不再需要）
data.drop(columns=['celebrity_homestate', 'celebrity_homecountry/region'], inplace=True)

# 查看合并后的数据
data[['celebrity_name', 'celebrity_homeland']].head()

      celebrity_name celebrity_homeland
0      John O'Hurley              Maine
1       Kelly Monaco       Pennsylvania
2  Evander Holyfield            Alabama
3      Rachel Hunter        New Zealand
4      Joey McIntyre      Massachusetts

In [109]:
import pandas as pd

# 假设你的原始数据已经加载到 DataFrame 中，名为 data_cleaned
# 对 `celebrity_industry` 和 `celebrity_homeland` 列同时进行 One-Hot 编码
data_cleaned = pd.get_dummies(data, columns=['celebrity_industry', 'celebrity_homeland'], drop_first=True)

# 查看结果
data_cleaned.head()

,celebrity_name,ballroom_partner,celebrity_age_during_season,season,results,placement,week1_judge1_score,week1_judge2_score,week1_judge3_score,week1_judge4_score,...,celebrity_homeland_Texas,celebrity_homeland_Utah,celebrity_homeland_Venezuela,celebrity_homeland_Virginia,celebrity_homeland_Wales,celebrity_homeland_Washington,celebrity_homeland_Washington D.C.,celebrity_homeland_West Virginia,celebrity_homeland_Wisconsin,celebrity_homeland_Yugoslavia
0,John O'Hurley,Charlotte Jorgensen,50,1,2nd Place,2,7.0,7.0,6.0,NaN,...,False,False,False,False,False,False,False,False,False,False
1,Kelly Monaco,Alec Mazo,29,1,1st Place,1,5.0,4.0,4.0,NaN,...,False,False,False,False,False,False,False,False,False,False
2,Evander Holyfield,Edyta Sliwinska,42,1,Eliminated Week 3,5,5.0,7.0,6.0,NaN,...,False,False,False,False,False,False,False,False,False,False
3,Rachel Hunter,Jonathan Roberts,35,1,Eliminated Week 4,4,7.0,6.0,7.0,NaN,...,False,False,False,False,False,False,False,False,False,False
4,Joey McIntyre,Ashly DelGrosso,32,1,3rd Place,3,7.0,7.0,6.0,NaN,...,False,False,False,False,False,False,False,False,False,False

In [111]:
import pandas as pd
import numpy as np

# 假设数据已经加载到 `data_cleaned` 数据框中

# 计算每一周评委评分的总和
weeks = [f'week{i}_judge{j}_score' for i in range(1, 12) for j in range(1, 5)]  # 假设有12周和4个评委

# 创建新列，存储每一周的总和和平均值
for week in range(1, 12):
    # 计算每周评委评分总和
    total_score_column = f'week{week}_total_score'
    data_cleaned[total_score_column] = data_cleaned[[f'week{week}_judge{j}_score' for j in range(1, 5)]].sum(axis=1)
    
    # 计算每周评委评分平均值
    avg_score_column = f'week{week}_avg_score'
    data_cleaned[avg_score_column] = data_cleaned[[f'week{week}_judge{j}_score' for j in range(1, 5)]].mean(axis=1)

# 检查数据，查看计算的总和和平均值
data_cleaned[['celebrity_name', 'season', 'week1_total_score', 'week1_avg_score', 'week2_total_score', 'week2_avg_score']].head()

,celebrity_name,season,week1_total_score,week1_avg_score,week2_total_score,week2_avg_score
0,John O'Hurley,1,20.0,6.666667,26.0,8.666667
1,Kelly Monaco,1,13.0,4.333333,17.0,5.666667
2,Evander Holyfield,1,18.0,6.000000,14.0,4.666667
3,Rachel Hunter,1,20.0,6.666667,24.0,8.000000
4,Joey McIntyre,1,20.0,6.666667,21.0,7.000000

In [178]:
import pandas as pd
import numpy as np

# 假设数据已经加载到 `data_cleaned` 数据框中
def calculate_avg_scores_before_elimination(df):
    avg_scores = []  # 存储所有选手的平均分

    # 遍历所有选手
    for index, row in df.iterrows():
        celebrity_name = row['celebrity_name']
        scores = []  # 用于存储每周的评分
        eliminated = False  # 用于标记选手是否被淘汰
        
        # 遍历每周的评分（最多11周）
        for week in range(1, 12):  # 11周的数据
            week_scores = []
            for judge in range(1, 5):  # 每周有4个评委评分
                score_column = f'week{week}_judge{judge}_score'
                
                if pd.notna(row[score_column]) and row[score_column] != 0:  # 如果该评分不是NaN且不为0
                    week_scores.append(row[score_column])
                
            if week_scores:  # 如果存在评分
                # 计算每周的评分平均值
                scores.append(np.mean(week_scores))
            
            # 如果某一周存在评委评分为0，标记为被淘汰
            if 0 in week_scores:
                eliminated = True
                break
        
        # 如果被淘汰，计算淘汰前的平均分
        if eliminated:
            avg_scores.append(np.mean(scores))  # 计算被淘汰前的评分平均值
        else:
            avg_scores.append(np.mean(scores))  # 未淘汰的选手计算平均值
    
    df['avg_scores_before_elimination'] = avg_scores
    return df

# 假设 `data_cleaned` 是你已经清理过的数据
# 调用函数计算每个选手的记忆项（被淘汰前的平均评分）
data_cleaned = calculate_avg_scores_before_elimination(data_cleaned)

# 检查生成的记忆项
data_cleaned[['celebrity_name', 'avg_scores_before_elimination']].head(20)

       celebrity_name  avg_scores_before_elimination
0       John O'Hurley                       8.055556
1        Kelly Monaco                       7.111111
2   Evander Holyfield                       5.000000
3       Rachel Hunter                       7.916667
4       Joey McIntyre                       7.033333
5       Trista Sutter                       6.166667
6        Tatum O'Neal                       6.666667
7         Tia Carrere                       7.666667
8     George Hamilton                       7.222222
9          Lisa Rinna                       8.023810
10      Stacy Keibler                       9.173604
11         Jerry Rice                       7.506942
12  Giselle Fernandez                       7.666667
13           Master P                       4.166667
14        Drew Lachey                       9.145825
15        Kenny Mayne                       4.333333
16       Harry Hamlin                       6.666667
17      Vivica A. Fox                       8.083333
18    Monique Coleman                       8.312500
19      Joey Lawrence                       8.629630

In [183]:
from sklearn.preprocessing import LabelEncoder

# 创建LabelEncoder对象
label_encoder = LabelEncoder()

# 对 `celebrity_name` 进行编号
data_cleaned['celebrity_name_encoded'] = label_encoder.fit_transform(data_cleaned['celebrity_name'])

# 对 `ballroom_partner` 进行编号
data_cleaned['ballroom_partner_encoded'] = label_encoder.fit_transform(data_cleaned['ballroom_partner'])


# 检查数据是否成功编码
data_cleaned[['celebrity_name', 'celebrity_name_encoded', 'ballroom_partner', 'ballroom_partner_encoded']].head()

,celebrity_name,celebrity_name_encoded,ballroom_partner,ballroom_partner_encoded
0,John O'Hurley,189,Charlotte Jorgensen,12
1,Kelly Monaco,212,Alec Mazo,2
2,Evander Holyfield,121,Edyta Sliwinska,21
3,Rachel Hunter,318,Jonathan Roberts,34
4,Joey McIntyre,188,Ashly DelGrosso,8

In [185]:
# 查看数据集的前5行
data_cleaned.head()

# 查看数据集的前10行
data_cleaned.head(10)

,celebrity_name,ballroom_partner,celebrity_age_during_season,season,placement,week1_judge1_score,week1_judge2_score,week1_judge3_score,week1_judge4_score,week2_judge1_score,...,celebrity_homeland_Wales,celebrity_homeland_Washington,celebrity_homeland_Washington D.C.,celebrity_homeland_West Virginia,celebrity_homeland_Wisconsin,celebrity_homeland_Yugoslavia,avg_scores_before_elimination,celebrity_name_encoded,ballroom_partner_encoded,avg_score_up_to_t
0,John O'Hurley,Charlotte Jorgensen,50,1,2,7.0,7.0,6.0,NaN,8.0,...,False,False,False,False,False,False,8.055556,189,12,8.055556
1,Kelly Monaco,Alec Mazo,29,1,1,5.0,4.0,4.0,NaN,5.0,...,False,False,False,False,False,False,7.111111,212,2,7.111111
2,Evander Holyfield,Edyta Sliwinska,42,1,5,5.0,7.0,6.0,NaN,5.0,...,False,False,False,False,False,False,5.000000,121,21,5.000000
3,Rachel Hunter,Jonathan Roberts,35,1,4,7.0,6.0,7.0,NaN,8.0,...,False,False,False,False,False,False,7.916667,318,34,7.916667
4,Joey McIntyre,Ashly DelGrosso,32,1,3,7.0,7.0,6.0,NaN,8.0,...,False,False,False,False,False,False,7.033333,188,8,7.033333
5,Trista Sutter,Louis van Amstel,32,1,6,6.0,6.0,6.0,NaN,6.0,...,False,False,False,False,False,False,6.166667,382,43,6.166667
6,Tatum O'Neal,Nick Kosovich,42,2,9,7.0,8.0,8.0,NaN,5.0,...,False,False,False,False,False,False,6.666667,367,46,6.666667
7,Tia Carrere,Maksim Chmerkoskiy,39,2,6,6.0,7.0,7.0,NaN,7.0,...,False,False,False,False,False,False,7.666667,374,44,7.666667
8,George Hamilton,Edyta Sliwinska,66,2,5,7.0,5.0,6.0,NaN,8.0,...,False,False,False,False,False,False,7.222222,129,21,7.222222
9,Lisa Rinna,Louis van Amstel,42,2,4,5.0,7.0,7.0,NaN,6.0,...,False,False,False,False,False,False,8.023810,239,43,7.888889

In [189]:


# 查看结果
data_cleaned.head()

,celebrity_name,ballroom_partner,celebrity_age_during_season,season,placement,week1_judge1_score,week1_judge2_score,week1_judge3_score,week1_judge4_score,week2_judge1_score,...,celebrity_homeland_Wales,celebrity_homeland_Washington,celebrity_homeland_Washington D.C.,celebrity_homeland_West Virginia,celebrity_homeland_Wisconsin,celebrity_homeland_Yugoslavia,avg_scores_before_elimination,celebrity_name_encoded,ballroom_partner_encoded,avg_score_up_to_t
0,John O'Hurley,Charlotte Jorgensen,50,1,2,7.0,7.0,6.0,NaN,8.0,...,False,False,False,False,False,False,8.055556,189,12,8.055556
1,Kelly Monaco,Alec Mazo,29,1,1,5.0,4.0,4.0,NaN,5.0,...,False,False,False,False,False,False,7.111111,212,2,7.111111
2,Evander Holyfield,Edyta Sliwinska,42,1,5,5.0,7.0,6.0,NaN,5.0,...,False,False,False,False,False,False,5.000000,121,21,5.000000
3,Rachel Hunter,Jonathan Roberts,35,1,4,7.0,6.0,7.0,NaN,8.0,...,False,False,False,False,False,False,7.916667,318,34,7.916667
4,Joey McIntyre,Ashly DelGrosso,32,1,3,7.0,7.0,6.0,NaN,8.0,...,False,False,False,False,False,False,7.033333,188,8,7.033333

In [191]:
# 保存新的数据到指定路径
data_cleaned.to_csv(r"C:\Users\ronny\Desktop\美赛\data\cleaned_data_with_name.csv", index=False)

In [193]:
##model building

In [233]:
import pandas as pd

# Load your cleaned data
data = pd.read_csv('cleaned_data_with_name.csv')  # Replace with your actual file path

# List of columns to delete
columns_to_delete = [
    "week1_total_score", "week1_avg_score", "week2_total_score", "week2_avg_score",
    "week3_total_score", "week3_avg_score", "week4_total_score", "week4_avg_score",
    "week5_total_score", "week5_avg_score", "week6_total_score", "week6_avg_score",
    "week7_total_score", "week7_avg_score", "week8_total_score", "week8_avg_score",
    "week9_total_score", "week9_avg_score", "week10_total_score", "week10_avg_score",
    "week11_total_score", "week11_avg_score","results_encoded"
]

# Drop the specified columns
data_cleaned = data.drop(columns=columns_to_delete)

import numpy as np
import pandas as pd

def add_avg_score_up_to_t(df, t, weeks_max=11, judges_max=4,
                          out_col="avg_score_up_to_t", treat_zero_as_missing=True):
    """
    计算每个选手“前 t 周的平均分”（先算每周评委均分，再对 1..t 周取平均）。
    - df: 宽表（包含 week{w}_judge{j}_score）
    - t: 当前周（实时预测时你知道当前是第几周）
    """
    t = int(t)
    t = max(1, min(t, weeks_max))

    weekly_mean_list = []
    for week in range(1, t + 1):
        judge_cols = [
            f"week{week}_judge{j}_score"
            for j in range(1, judges_max + 1)
            if f"week{week}_judge{j}_score" in df.columns
        ]
        if not judge_cols:
            continue

        scores = df[judge_cols].copy()
        if treat_zero_as_missing:
            scores = scores.replace(0, np.nan)

        # 该周评委均分（每行一个选手）
        weekly_mean_list.append(scores.mean(axis=1, skipna=True))

    if not weekly_mean_list:
        df[out_col] = np.nan
        return df

    # 前 t 周均分：对每周均分再取平均
    df[out_col] = pd.concat(weekly_mean_list, axis=1).mean(axis=1, skipna=True)
    return df

# ===== 用法示例 =====
current_week = 6  # 你预测时处于第几周，就填几（实时预测场景一定知道）
data_cleaned = add_avg_score_up_to_t(data_cleaned, t=current_week, out_col="avg_score_up_to_t")

# 看一下结果
data_cleaned[["celebrity_name", "avg_score_up_to_t"]].head(10)


# Save the cleaned data to a new file
data_cleaned.to_csv('cleaned_data_2.csv', index=False)

In [235]:
data_cleaned.to_csv(r"C:\Users\ronny\Desktop\美赛\data\cleaned_data_2.csv", index=False)

In [237]:
data_cleaned.head()

,celebrity_name,ballroom_partner,celebrity_age_during_season,season,placement,week1_judge1_score,week1_judge2_score,week1_judge3_score,week1_judge4_score,week2_judge1_score,...,celebrity_homeland_Wales,celebrity_homeland_Washington,celebrity_homeland_Washington D.C.,celebrity_homeland_West Virginia,celebrity_homeland_Wisconsin,celebrity_homeland_Yugoslavia,avg_scores_before_elimination,celebrity_name_encoded,ballroom_partner_encoded,avg_score_up_to_t
0,John O'Hurley,Charlotte Jorgensen,50,1,2,7.0,7.0,6.0,NaN,8.0,...,False,False,False,False,False,False,8.055556,189,12,8.055556
1,Kelly Monaco,Alec Mazo,29,1,1,5.0,4.0,4.0,NaN,5.0,...,False,False,False,False,False,False,7.111111,212,2,7.111111
2,Evander Holyfield,Edyta Sliwinska,42,1,5,5.0,7.0,6.0,NaN,5.0,...,False,False,False,False,False,False,5.000000,121,21,5.000000
3,Rachel Hunter,Jonathan Roberts,35,1,4,7.0,6.0,7.0,NaN,8.0,...,False,False,False,False,False,False,7.916667,318,34,7.916667
4,Joey McIntyre,Ashly DelGrosso,32,1,3,7.0,7.0,6.0,NaN,8.0,...,False,False,False,False,False,False,7.033333,188,8,7.033333

In [239]:
import pandas as pd

# 读取原始数据（请替换为实际的文件路径）
data = pd.read_csv('cleaned_data_2.csv')  # 用实际路径替换

# 创建一个空列表来存储新的数据
partner_ability_data = []

# 获取编号和名字的对应关系
celebrity_name_mapping = data[['celebrity_name_encoded', 'celebrity_name']].drop_duplicates()
partner_name_mapping = data[['ballroom_partner_encoded', 'ballroom_partner']].drop_duplicates()

# 遍历每个舞伴
for partner in data['ballroom_partner_encoded'].unique():
    # 选择该舞伴的数据
    partner_data = data[data['ballroom_partner_encoded'] == partner]
    
    # 获取舞伴名字
    partner_name = partner_name_mapping[partner_name_mapping['ballroom_partner_encoded'] == partner]['ballroom_partner'].values[0]
    
    # 遍历该舞伴与所有明星的合作
    for _, row in partner_data.iterrows():
        # 获取合作明星的编码和对应的排名
        celebrity_name_encoded = row['celebrity_name_encoded']
        placement = row['placement']
        
        # 获取明星名字
        celebrity_name = celebrity_name_mapping[celebrity_name_mapping['celebrity_name_encoded'] == celebrity_name_encoded]['celebrity_name'].values[0]
        
        # 将每个舞伴与明星的合作记录到新数据中
        partner_ability_data.append([partner_name, celebrity_name, placement])

# 创建一个新的 DataFrame 来存储合作数据
partner_ability_df = pd.DataFrame(partner_ability_data, columns=['ballroom_partner', 'celebrity_name', 'placement'])

# 将结果保存为 partner_ability.csv 文件
partner_ability_df.to_csv('partner_ability.csv', index=False)

In [ ]:
###############检查

In [243]:
print("avg_score_up_to_t in data_cleaned?", "avg_score_up_to_t" in data_cleaned.columns)
print("data_cleaned shape:", data_cleaned.shape)
print(data_cleaned[["celebrity_name", "avg_score_up_to_t"]].head(3))

avg_score_up_to_t in data_cleaned? True
data_cleaned shape: (421, 147)
      celebrity_name  avg_score_up_to_t
0      John O'Hurley           8.055556
1       Kelly Monaco           7.111111
2  Evander Holyfield           5.000000

In [245]:
tmp = pd.read_csv("cleaned_data_2.csv")
print("avg_score_up_to_t in cleaned_data_2.csv?", "avg_score_up_to_t" in tmp.columns)
print("tmp shape:", tmp.shape)
print(tmp[["celebrity_name", "avg_score_up_to_t"]].head(3))

avg_score_up_to_t in cleaned_data_2.csv? True
tmp shape: (421, 147)
      celebrity_name  avg_score_up_to_t
0      John O'Hurley           8.055556
1       Kelly Monaco           7.111111
2  Evander Holyfield           5.000000

In [247]:
print([c for c in tmp.columns if "avg" in c.lower()])

['avg_scores_before_elimination', 'avg_score_up_to_t']

In [ ]:
#############检查结束

In [249]:
import pandas as pd

# 读取原始数据（请替换为实际的文件路径）
data = pd.read_csv('cleaned_data_2.csv')  # 用实际路径替换

# 获取编号和名字的对应关系
name_mapping = data[['celebrity_name_encoded', 'celebrity_name']].drop_duplicates()

# 显示编号与名字的对应关系
print(name_mapping)

     celebrity_name_encoded     celebrity_name
0                       189      John O'Hurley
1                       212       Kelly Monaco
2                       121  Evander Holyfield
3                       318      Rachel Hunter
4                       188      Joey McIntyre
..                      ...                ...
416                     343       Scott Hoying
417                      12         Alix Earle
418                     171        Jen Affleck
419                     401    Whitney Leavitt
420                     112        Dylan Efron

[408 rows x 2 columns]

In [251]:
partner_ability_df = pd.DataFrame(partner_ability_data, columns=['ballroom_partner', 'celebrity_name', 'placement'])

In [253]:
# 假设每个舞伴和明星的合作数据已经存在partner_ability_df中
# 计算每个舞伴的平均排名
partner_avg_placement = partner_ability_df.groupby('ballroom_partner')['placement'].mean().reset_index()

# 计算加权系数（这里假设排名越低代表越强）
partner_avg_placement['weight'] = 1 / partner_avg_placement['placement']

# 标准化权重（可选）
partner_avg_placement['normalized_weight'] = (partner_avg_placement['weight'] - partner_avg_placement['weight'].min()) / (partner_avg_placement['weight'].max() - partner_avg_placement['weight'].min())

# 将结果保存为CSV文件
partner_avg_placement.to_csv('partner_weights.csv', index=False)

In [210]:
# 读取主数据集（请替换为实际路径）
data = pd.read_csv('cleaned_data_2.csv')  # 用实际路径替换

# 读取舞伴权重数据
partner_weights = pd.read_csv('partner_weights.csv')

# 合并主数据集与舞伴权重数据，基于舞伴编码
data = data.merge(partner_weights[['ballroom_partner', 'normalized_weight']], 
                  how='left', 
                  on='ballroom_partner')

# 将新的数据保存为文件
data.to_csv('data_with_partner_strength.csv', index=False)
data_cleaned.to_csv(r"C:\Users\ronny\Desktop\美赛\data\data_with_partner_strength.csv", index=False)

In [255]:
import pandas as pd

df = pd.read_csv("data_with_partner_strength.csv")
print(df.shape)
print(df.columns)

(421, 148)
Index(['celebrity_name', 'ballroom_partner', 'celebrity_age_during_season',
       'season', 'placement', 'week1_judge1_score', 'week1_judge2_score',
       'week1_judge3_score', 'week1_judge4_score', 'week2_judge1_score',
       ...
       'celebrity_homeland_Washington', 'celebrity_homeland_Washington D.C.',
       'celebrity_homeland_West Virginia', 'celebrity_homeland_Wisconsin',
       'celebrity_homeland_Yugoslavia', 'avg_scores_before_elimination',
       'celebrity_name_encoded', 'ballroom_partner_encoded',
       'avg_score_up_to_t', 'normalized_weight'],
      dtype='object', length=148)

In [257]:
import pandas as pd
import numpy as np

# 读取数据（确保文件路径正确）
data = pd.read_csv('data_with_partner_strength.csv')

# 计算每一周评委评分的方差
def calculate_weekly_variance(df):
    # 为每一周的方差创建一个新的列
    for week in range(1, 12):  # 遍历11周
        week_scores = []  # 用于存储该周所有选手的方差
        
        # 遍历每个选手
        for index, row in df.iterrows():
            week_column_scores = []
            for judge in range(1, 5):  # 每周有4个评委评分
                score_column = f'week{week}_judge{judge}_score'
                
                if pd.notna(row[score_column]) and row[score_column] != 0:  # 如果该评分不是NaN且不为0
                    week_column_scores.append(row[score_column])
            
            # 如果该选手该周有评分，计算方差，否则填充NaN
            if week_column_scores:  # 如果有有效评分
                week_scores.append(np.var(week_column_scores))  # 每个选手该周的方差
            else:
                week_scores.append(np.nan)  # 如果没有评分，填充NaN
        
        # 确保列长度与原数据框一致
        if len(week_scores) < len(df):
            week_scores.extend([np.nan] * (len(df) - len(week_scores)))
        
        # 将计算的方差作为新的列加入数据框
        df[f'week{week}_variance'] = week_scores
    
    return df

# 调用函数计算每个选手每周的评分方差
data = calculate_weekly_variance(data)

# 检查生成的方差列
print(data[['celebrity_name', 'week1_variance', 'week2_variance', 'week3_variance', 'week4_variance', 'week5_variance', 'week6_variance', 'week7_variance', 'week8_variance', 'week9_variance', 'week10_variance', 'week11_variance']].head(20))

       celebrity_name  week1_variance  week2_variance  week3_variance  \
0       John O'Hurley        0.222222        0.222222        0.666667
1        Kelly Monaco        0.222222        0.222222        0.666667
2   Evander Holyfield        0.666667        0.222222        0.222222
3       Rachel Hunter        0.222222        0.000000        0.222222
4       Joey McIntyre        0.222222        0.666667        0.222222
5       Trista Sutter        0.000000        0.222222             NaN
6        Tatum O'Neal        0.222222        0.222222             NaN
7         Tia Carrere        0.222222        0.222222        0.222222
8     George Hamilton        0.666667        0.222222        0.222222
9          Lisa Rinna        0.888889        0.222222        0.222222
10      Stacy Keibler        0.888889        0.222222        0.000000
11         Jerry Rice        0.000000        0.222222        0.222222
12  Giselle Fernandez        0.222222        0.000000        0.222222
13           Master P        0.000000        0.222222        0.888889
14        Drew Lachey        0.000000        0.000000        0.000000
15        Kenny Mayne        0.222222             NaN             NaN
16       Harry Hamlin        0.222222        0.000000        0.222222
17      Vivica A. Fox        0.888889        0.000000        0.000000
18    Monique Coleman        0.222222        0.222222        0.000000
19      Joey Lawrence        0.000000        0.222222        0.888889

    week4_variance  week5_variance  week6_variance  week7_variance  \
0         0.666667        0.000000        0.000000             NaN
1         0.222222        0.222222        0.222222             NaN
2              NaN             NaN             NaN             NaN
3         0.888889             NaN             NaN             NaN
4         0.222222        0.500000             NaN             NaN
5              NaN             NaN             NaN             NaN
6              NaN             NaN             NaN             NaN
7         0.222222        0.222222             NaN             NaN
8         0.000000        0.000000        0.222222             NaN
9         0.222222        0.888889        0.000000        0.055556
10        0.222222        0.000000        0.000000        0.055556
11        0.000000        0.222222        0.222222        0.055556
12             NaN             NaN             NaN             NaN
13        0.888889             NaN             NaN             NaN
14        0.222222        0.000000        0.000000        0.055556
15             NaN             NaN             NaN             NaN
16             NaN             NaN             NaN             NaN
17        0.000000             NaN             NaN             NaN
18        0.000000        0.000000        0.888889        0.000000
19        0.000000        0.222222        0.000000        0.166667

    week8_variance  week9_variance  week10_variance  week11_variance
0              NaN             NaN              NaN              NaN
1              NaN             NaN              NaN              NaN
2              NaN             NaN              NaN              NaN
3              NaN             NaN              NaN              NaN
4              NaN             NaN              NaN              NaN
5              NaN             NaN              NaN              NaN
6              NaN             NaN              NaN              NaN
7              NaN             NaN              NaN              NaN
8              NaN             NaN              NaN              NaN
9              NaN             NaN              NaN              NaN
10        0.024686             NaN              NaN              NaN
11        0.024701             NaN              NaN              NaN
12             NaN             NaN              NaN              NaN
13             NaN             NaN              NaN              NaN
14        0.000000             NaN              NaN              NaN
15             NaN             NaN              NaN              NaN
16             NaN             NaN              NaN              NaN
17             NaN             NaN              NaN              NaN
18        0.055556             NaN              NaN              NaN
19        0.166667        0.055556              NaN              NaN

In [259]:
# 计算方差的标准差
variance_std = np.std(variance_values)

# 设置一个阈值（方差超过2倍标准差视为争议）
threshold = np.mean(variance_values) + 3 * variance_std

# 为每场表演计算是否超出阈值
def calculate_controversy_using_threshold(df, threshold):
    controversy_data = []
    for week in range(1, 12):  # 11周
        for index, row in df.iterrows():
            week_column_scores = []
            for judge in range(1, 5):  # 每周有4个评委评分
                score_column = f'week{week}_judge{judge}_score'
                
                if pd.notna(row[score_column]) and row[score_column] != 0:  # 如果该评分不是NaN且不为0
                    week_column_scores.append(row[score_column])
            
            if week_column_scores:  # 如果该周有评分，计算方差
                variance = np.var(week_column_scores)  # 当前表演的方差
                
                # 判断是否超出方差阈值
                if variance > threshold:
                    controversy_data.append([row['celebrity_name'], week, variance, True])
                else:
                    controversy_data.append([row['celebrity_name'], week, variance, False])
    
    controversy_df = pd.DataFrame(controversy_data, columns=['celebrity_name', 'week', 'variance', 'is_controversial'])
    return controversy_df

# 使用标准差阈值来计算争议
controversy_df_threshold = calculate_controversy_using_threshold(data, threshold)

# 检查结果
print(controversy_df_threshold.head(60))

           celebrity_name  week  variance  is_controversial
0           John O'Hurley     1  0.222222             False
1            Kelly Monaco     1  0.222222             False
2       Evander Holyfield     1  0.666667             False
3           Rachel Hunter     1  0.222222             False
4           Joey McIntyre     1  0.222222             False
5           Trista Sutter     1  0.000000             False
6            Tatum O'Neal     1  0.222222             False
7             Tia Carrere     1  0.222222             False
8         George Hamilton     1  0.666667             False
9              Lisa Rinna     1  0.888889              True
10          Stacy Keibler     1  0.888889              True
11             Jerry Rice     1  0.000000             False
12      Giselle Fernandez     1  0.222222             False
13               Master P     1  0.000000             False
14            Drew Lachey     1  0.000000             False
15            Kenny Mayne     1  0.222222             False
16           Harry Hamlin     1  0.222222             False
17          Vivica A. Fox     1  0.888889              True
18        Monique Coleman     1  0.222222             False
19          Joey Lawrence     1  0.000000             False
20            Mario Lopez     1  0.222222             False
21           Emmitt Smith     1  0.000000             False
22         Shanna Moakler     1  0.666667             False
23             Willa Ford     1  0.222222             False
24             Sara Evans     1  0.000000             False
25         Jerry Springer     1  0.222222             False
26         Tucker Carlson     1  0.666667             False
27      John Ratzenberger     1  0.222222             False
28            Ian Ziering     1  0.000000             False
29          Clyde Drexler     1  0.222222             False
30              Laila Ali     1  0.222222             False
31       Apolo Anton Ohno     1  0.000000             False
32       Shandi Finnessey     1  0.222222             False
33      Paulina Porizkova     1  0.222222             False
34          Heather Mills     1  0.000000             False
35        Billy Ray Cyrus     1  0.222222             False
36            Joey Fatone     1  0.000000             False
37          Leeza Gibbons     1  0.000000             False
38       Cameron Mathison     1  0.000000             False
39           Jane Seymour     1  0.000000             False
40          Sabrina Bryan     1  0.222222             False
41           Jennie Garth     1  0.000000             False
42  Floyd Mayweather Jr.      1  0.000000             False
43            Josie Maran     1  0.222222             False
44            Albert Reed     1  0.000000             False
45      Helio Castroneves     1  0.222222             False
46                  Mel B     1  0.000000             False
47           Wayne Newton     1  0.222222             False
48           Marie Osmond     1  0.000000             False
49             Mark Cuban     1  0.000000             False
50  Cristian de la Fuente     1  0.000000             False
51       Steve Guttenberg     1  0.000000             False
52      Priscilla Presley     1  0.000000             False
53          Marlee Matlin     1  0.222222             False
54      Shannon Elizabeth     1  0.000000             False
55  Marissa Jaret Winokur     1  0.000000             False
56           Jason Taylor     1  0.222222             False
57       Kristi Yamaguchi     1  0.000000             False
58           Monica Seles     1  0.000000             False
59          Penn Jillette     1  0.222222             False

In [217]:
# 筛选出所有争议的表演
controversial_shows = controversy_df_threshold[controversy_df_threshold['is_controversial'] == True]

# 保存争议表演的数据到新文件
controversial_shows[['celebrity_name', 'week', 'variance']].to_csv('controversial_shows.csv', index=False)

# 检查保存的文件
print(controversial_shows[['celebrity_name', 'week', 'variance']].head(60))

              celebrity_name  week  variance
9                 Lisa Rinna     1  0.888889
10             Stacy Keibler     1  0.888889
17             Vivica A. Fox     1  0.888889
71                Lance Bass     1  0.722222
101                      Mya     1  2.000000
111       Nicole Scherzinger     1  0.888889
120              Kurt Warner     1  0.888889
271              Vanilla Ice     1  0.687500
272              Jana Kramer     1  0.687500
326               Lamar Odom     1  0.888889
355            Iman Shumpert     1  1.187500
525       Nicole Scherzinger     2  0.888889
562             William Levy     2  0.888889
571            Gladys Knight     2  0.888889
615            Charlie White     2  0.888889
685           Heather Morris     2  0.750000
687            Bonner Bolton     2  1.500000
694               Nick Viall     2  0.687500
738             Karamo Brown     2  0.888889
759   Mike "The Miz" Mizanin     2  0.750000
836                 Master P     3  0.888889
841            Joey Lawrence     3  0.888889
842              Mario Lopez     3  0.888889
903               Louie Vito     3  1.555556
908                      Mya     3  2.000000
917       Nicole Scherzinger     3  1.555556
1010             Tommy Chong     3  0.750000
1011          Betsey Johnson     3  1.187500
1017             Riker Lynch     3  0.750000
1072           Jordan Fisher     3  0.888889
1082           Chris Mazdzer     3  0.687500
1130            Jimmie Allen     3  0.888889
1159        Mauricio Umansky     3  0.687500
1187           Rachel Hunter     4  0.888889
1194                Master P     4  0.888889
1242         Lawrence Taylor     4  0.888889
1259                     Mya     4  0.888889
1340           Charlie White     4  0.687500
1434              Lamar Odom     4  1.500000
1516              Lisa Rinna     5  0.888889
1587             Kyle Massey     5  1.555556
1640             Amber Riley     5  1.555556
1681              Kim Fields     5  1.000000
1735            Hannah Brown     5  0.888889
1806         Monique Coleman     6  0.888889
1838            Brooke Burke     6  0.888889
1844                Lil' Kim     6  0.888889
1845                 Steve-O     6  1.555556
1850           Michael Irvin     6  0.888889
1860      Nicole Scherzinger     6  1.555556
1861            Erin Andrews     6  0.888889
1912             Amber Riley     6  0.888889
1927           Janel Parrish     6  0.687500
1932         Sadie Robertson     6  0.687500
1983              Drew Scott     6  0.750000
2091              Lance Bass     7  0.888889
2253             Olivia Jade     7  0.750000
2351          Maria Menounos     8  0.888889
2363          Kellie Pickler     8  0.722222

In [219]:
# 查看数据框的前5行
print(data.head())

      celebrity_name     ballroom_partner  celebrity_age_during_season  \
0      John O'Hurley  Charlotte Jorgensen                           50
1       Kelly Monaco            Alec Mazo                           29
2  Evander Holyfield      Edyta Sliwinska                           42
3      Rachel Hunter     Jonathan Roberts                           35
4      Joey McIntyre      Ashly DelGrosso                           32

   season  placement  week1_judge1_score  week1_judge2_score  \
0       1          2                 7.0                 7.0
1       1          1                 5.0                 4.0
2       1          5                 5.0                 7.0
3       1          4                 7.0                 6.0
4       1          3                 7.0                 7.0

   week1_judge3_score  week1_judge4_score  week2_judge1_score  ...  \
0                 6.0                 NaN                 8.0  ...
1                 4.0                 NaN                 5.0  ...
2                 6.0                 NaN                 5.0  ...
3                 7.0                 NaN                 8.0  ...
4                 6.0                 NaN                 8.0  ...

   week2_variance  week3_variance  week4_variance  week5_variance  \
0        0.222222        0.666667        0.666667        0.000000
1        0.222222        0.666667        0.222222        0.222222
2        0.222222        0.222222             NaN             NaN
3        0.000000        0.222222        0.888889             NaN
4        0.666667        0.222222        0.222222        0.500000

   week6_variance  week7_variance  week8_variance  week9_variance  \
0        0.000000             NaN             NaN             NaN
1        0.222222             NaN             NaN             NaN
2             NaN             NaN             NaN             NaN
3             NaN             NaN             NaN             NaN
4             NaN             NaN             NaN             NaN

   week10_variance  week11_variance
0              NaN              NaN
1              NaN              NaN
2              NaN              NaN
3              NaN              NaN
4              NaN              NaN

[5 rows x 159 columns]

In [261]:
import pandas as pd

# 读取数据
data = pd.read_csv('data_with_partner_strength.csv')

# 创建一个新的列，存储每个选手的淘汰周数
elimination_weeks = []

# 遍历每个选手
for index, row in data.iterrows():
    celebrity_name = row['celebrity_name']
    
    # 初始化淘汰周数为NaN
    eliminated_week = None
    
    # 遍历每周的评分（假设有11周）
    for week in range(1, 12):
        week_column_scores = []
        
        # 获取每周的4个评委评分
        for judge in range(1, 5):  # 每周有4个评委评分
            score_column = f'week{week}_judge{judge}_score'
            
            if pd.notna(row[score_column]) and row[score_column] != 0:  # 如果该评分不是NaN且不为0
                week_column_scores.append(row[score_column])
        
        # 检查是否有评委评分为0，如果有，则该选手被淘汰，记录淘汰周数
        if len(week_column_scores) == 0:  # 如果该周所有评委评分都是0
            eliminated_week = week
            break
    
    # 将淘汰周数添加到列表中
    elimination_weeks.append(eliminated_week)

# 将淘汰周数添加到数据框中
data['eliminated_week'] = elimination_weeks

# 保存更新后的数据框到新的CSV文件
data.to_csv('data_with_eliminated_week.csv', index=False)

# 查看更新后的数据框
print(data[['celebrity_name', 'eliminated_week']].head(50))

           celebrity_name  eliminated_week
0           John O'Hurley              7.0
1            Kelly Monaco              7.0
2       Evander Holyfield              4.0
3           Rachel Hunter              5.0
4           Joey McIntyre              6.0
5           Trista Sutter              3.0
6            Tatum O'Neal              3.0
7             Tia Carrere              6.0
8         George Hamilton              7.0
9              Lisa Rinna              8.0
10          Stacy Keibler              9.0
11             Jerry Rice              9.0
12      Giselle Fernandez              4.0
13               Master P              5.0
14            Drew Lachey              9.0
15            Kenny Mayne              2.0
16           Harry Hamlin              4.0
17          Vivica A. Fox              5.0
18        Monique Coleman              9.0
19          Joey Lawrence             10.0
20            Mario Lopez             11.0
21           Emmitt Smith             11.0
22         Shanna Moakler              3.0
23             Willa Ford              6.0
24             Sara Evans              6.0
25         Jerry Springer              8.0
26         Tucker Carlson              2.0
27      John Ratzenberger              8.0
28            Ian Ziering             10.0
29          Clyde Drexler              6.0
30              Laila Ali             11.0
31       Apolo Anton Ohno             11.0
32       Shandi Finnessey              4.0
33      Paulina Porizkova              3.0
34          Heather Mills              7.0
35        Billy Ray Cyrus              9.0
36            Joey Fatone             11.0
37          Leeza Gibbons              5.0
38       Cameron Mathison              9.0
39           Jane Seymour              8.0
40          Sabrina Bryan              7.0
41           Jennie Garth             10.0
42  Floyd Mayweather Jr.               5.0
43            Josie Maran              2.0
44            Albert Reed              3.0
45      Helio Castroneves             11.0
46                  Mel B             11.0
47           Wayne Newton              4.0
48           Marie Osmond             11.0
49             Mark Cuban              6.0

In [263]:
import pandas as pd

# 读取数据
data = pd.read_csv('data_with_eliminated_week.csv')  # 包含选手和淘汰周数的数据
controversial_shows = pd.read_csv('controversial_shows.csv')  # 包含争议表演数据

# 合并两个数据集：基于 'celebrity_name' 和 'week' 列
merged_data = pd.merge(controversial_shows, data[['celebrity_name', 'eliminated_week']], on='celebrity_name', how='left')

# 计算 eliminated_week 和 week 之间的差值
merged_data['week_difference'] = merged_data['eliminated_week'] - merged_data['week']

# 筛选出差值大于1的选手
eliminated_later_than_one = merged_data[merged_data['week_difference'] > 1]

# 查看结果
print(eliminated_later_than_one[['celebrity_name', 'week', 'eliminated_week', 'week_difference']])

# 如果需要保存筛选结果
eliminated_later_than_one.to_csv('eliminated_later_than_one.csv', index=False)

            celebrity_name  week  eliminated_week  week_difference
0               Lisa Rinna     1              8.0              7.0
1            Stacy Keibler     1              9.0              8.0
2            Vivica A. Fox     1              5.0              4.0
3               Lance Bass     1             11.0             10.0
4                      Mya     1             11.0             10.0
5       Nicole Scherzinger     1             11.0             10.0
6              Kurt Warner     1              9.0              8.0
7              Vanilla Ice     1              5.0              4.0
9               Lamar Odom     1              5.0              4.0
10           Iman Shumpert     1             11.0             10.0
11      Nicole Scherzinger     2             11.0              9.0
12            William Levy     2             11.0              9.0
13           Gladys Knight     2              7.0              5.0
14           Charlie White     2             10.0              8.0
15          Heather Morris     2              7.0              5.0
16           Bonner Bolton     2              9.0              7.0
17              Nick Viall     2              8.0              6.0
18            Karamo Brown     2              8.0              6.0
19  Mike "The Miz" Mizanin     2              8.0              6.0
20                Master P     3              5.0              2.0
21           Joey Lawrence     3             10.0              7.0
22             Mario Lopez     3             11.0              8.0
23              Louie Vito     3              7.0              4.0
24                     Mya     3             11.0              8.0
25      Nicole Scherzinger     3             11.0              8.0
26             Tommy Chong     3             11.0              8.0
27          Betsey Johnson     3              5.0              2.0
28             Riker Lynch     3             11.0              8.0
29           Jordan Fisher     3             11.0              8.0
31            Jimmie Allen     3              9.0              6.0
32        Mauricio Umansky     3              7.0              4.0
35         Lawrence Taylor     4              8.0              4.0
36                     Mya     4             11.0              7.0
37           Charlie White     4             10.0              6.0
39              Lisa Rinna     5              8.0              3.0
40             Kyle Massey     5             11.0              6.0
42              Kim Fields     5              8.0              3.0
44         Monique Coleman     6              9.0              3.0
45            Brooke Burke     6             11.0              5.0
46                Lil' Kim     6             10.0              4.0
48           Michael Irvin     6              8.0              2.0
49      Nicole Scherzinger     6             11.0              5.0
50            Erin Andrews     6             11.0              5.0
54              Drew Scott     6             11.0              5.0
55              Lance Bass     7             11.0              4.0
56             Olivia Jade     7              9.0              2.0
57          Maria Menounos     8             10.0              2.0
58          Kellie Pickler     8             11.0              3.0

In [265]:
import pandas as pd
import numpy as np

# 读取数据
data = pd.read_csv('data_with_partner_strength.csv')

# 计算每一周评委评分的方差
def calculate_weekly_variance(df):
    # 为每一周的方差创建一个新的列
    for week in range(1, 12):  # 遍历11周
        week_scores = []  # 存储该周所有选手的方差
        
        # 遍历每个选手
        for index, row in df.iterrows():
            week_column_scores = []
            for judge in range(1, 5):  # 每周有4个评委评分
                score_column = f'week{week}_judge{judge}_score'
                
                if pd.notna(row[score_column]) and row[score_column] != 0:  # 如果该评分不是NaN且不为0
                    week_column_scores.append(row[score_column])
            
            # 如果该选手该周有评分，计算方差，否则填充NaN
            if week_column_scores:  # 如果有有效评分
                week_scores.append(np.var(week_column_scores))  # 每个选手该周的方差
            else:
                week_scores.append(np.nan)  # 如果没有评分，填充NaN
        
        # 将计算的方差作为新的列加入数据框
        df[f'week{week}_variance'] = week_scores
    
    return df

# 计算每个选手每周的评分方差
data = calculate_weekly_variance(data)

# 保存更新后的数据框到新的 CSV 文件
data.to_csv('data_with_variance_added.csv', index=False)

# 查看更新后的数据框
print(data[['celebrity_name', 'week1_variance', 'week2_variance', 'week3_variance', 'week4_variance', 'week5_variance', 'week6_variance', 'week7_variance', 'week8_variance', 'week9_variance', 'week10_variance', 'week11_variance']].head(20))

       celebrity_name  week1_variance  week2_variance  week3_variance  \
0       John O'Hurley        0.222222        0.222222        0.666667
1        Kelly Monaco        0.222222        0.222222        0.666667
2   Evander Holyfield        0.666667        0.222222        0.222222
3       Rachel Hunter        0.222222        0.000000        0.222222
4       Joey McIntyre        0.222222        0.666667        0.222222
5       Trista Sutter        0.000000        0.222222             NaN
6        Tatum O'Neal        0.222222        0.222222             NaN
7         Tia Carrere        0.222222        0.222222        0.222222
8     George Hamilton        0.666667        0.222222        0.222222
9          Lisa Rinna        0.888889        0.222222        0.222222
10      Stacy Keibler        0.888889        0.222222        0.000000
11         Jerry Rice        0.000000        0.222222        0.222222
12  Giselle Fernandez        0.222222        0.000000        0.222222
13           Master P        0.000000        0.222222        0.888889
14        Drew Lachey        0.000000        0.000000        0.000000
15        Kenny Mayne        0.222222             NaN             NaN
16       Harry Hamlin        0.222222        0.000000        0.222222
17      Vivica A. Fox        0.888889        0.000000        0.000000
18    Monique Coleman        0.222222        0.222222        0.000000
19      Joey Lawrence        0.000000        0.222222        0.888889

    week4_variance  week5_variance  week6_variance  week7_variance  \
0         0.666667        0.000000        0.000000             NaN
1         0.222222        0.222222        0.222222             NaN
2              NaN             NaN             NaN             NaN
3         0.888889             NaN             NaN             NaN
4         0.222222        0.500000             NaN             NaN
5              NaN             NaN             NaN             NaN
6              NaN             NaN             NaN             NaN
7         0.222222        0.222222             NaN             NaN
8         0.000000        0.000000        0.222222             NaN
9         0.222222        0.888889        0.000000        0.055556
10        0.222222        0.000000        0.000000        0.055556
11        0.000000        0.222222        0.222222        0.055556
12             NaN             NaN             NaN             NaN
13        0.888889             NaN             NaN             NaN
14        0.222222        0.000000        0.000000        0.055556
15             NaN             NaN             NaN             NaN
16             NaN             NaN             NaN             NaN
17        0.000000             NaN             NaN             NaN
18        0.000000        0.000000        0.888889        0.000000
19        0.000000        0.222222        0.000000        0.166667

    week8_variance  week9_variance  week10_variance  week11_variance
0              NaN             NaN              NaN              NaN
1              NaN             NaN              NaN              NaN
2              NaN             NaN              NaN              NaN
3              NaN             NaN              NaN              NaN
4              NaN             NaN              NaN              NaN
5              NaN             NaN              NaN              NaN
6              NaN             NaN              NaN              NaN
7              NaN             NaN              NaN              NaN
8              NaN             NaN              NaN              NaN
9              NaN             NaN              NaN              NaN
10        0.024686             NaN              NaN              NaN
11        0.024701             NaN              NaN              NaN
12             NaN             NaN              NaN              NaN
13             NaN             NaN              NaN              NaN
14        0.000000             NaN              NaN              NaN
15             NaN             NaN              NaN              NaN
16             NaN             NaN              NaN              NaN
17             NaN             NaN              NaN              NaN
18        0.055556             NaN              NaN              NaN
19        0.166667        0.055556              NaN              NaN

In [208]:
import pandas as pd

# 读取更新后的数据
data = pd.read_csv('data_with_variance_added.csv')

# 设置方差阈值
threshold = 0.68

# 列出所有 weekX_variance 列（总共11周，每周4个评委）
variance_columns = [
    'week1_variance', 'week2_variance', 'week3_variance', 'week4_variance', 'week5_variance',
    'week6_variance', 'week7_variance', 'week8_variance', 'week9_variance', 'week10_variance', 'week11_variance'
]

# 为每个 weekX_variance 列生成争议标签
for variance_column in variance_columns:
    controversy_label = []
    
    for index, row in data.iterrows():
        variance = row[variance_column]
        
        # 如果方差大于阈值0.68，则标记为True，否则为False
        if pd.notna(variance) and variance > threshold:
            controversy_label.append(True)
        else:
            controversy_label.append(False)
    
    # 将争议标签添加到数据框中
    data[f'{variance_column}_contr'] = controversy_label

# 保存更新后的数据框
data.to_csv('data_with_controversy_labels.csv', index=False)
data.to_csv(r"C:\Users\ronny\Desktop\美赛\data\data_with_controversy_labels.csv", index=False)

# 查看最终结果（显示前20行）
print(data[['celebrity_name'] + [f'{col}_contr' for col in variance_columns]].head(20))

       celebrity_name  week1_variance_contr  week2_variance_contr  \
0       John O'Hurley                 False                 False
1        Kelly Monaco                 False                 False
2   Evander Holyfield                 False                 False
3       Rachel Hunter                 False                 False
4       Joey McIntyre                 False                 False
5       Trista Sutter                 False                 False
6        Tatum O'Neal                 False                 False
7         Tia Carrere                 False                 False
8     George Hamilton                 False                 False
9          Lisa Rinna                  True                 False
10      Stacy Keibler                  True                 False
11         Jerry Rice                 False                 False
12  Giselle Fernandez                 False                 False
13           Master P                 False                 False
14        Drew Lachey                 False                 False
15        Kenny Mayne                 False                 False
16       Harry Hamlin                 False                 False
17      Vivica A. Fox                  True                 False
18    Monique Coleman                 False                 False
19      Joey Lawrence                 False                 False

    week3_variance_contr  week4_variance_contr  week5_variance_contr  \
0                  False                 False                 False
1                  False                 False                 False
2                  False                 False                 False
3                  False                  True                 False
4                  False                 False                 False
5                  False                 False                 False
6                  False                 False                 False
7                  False                 False                 False
8                  False                 False                 False
9                  False                 False                  True
10                 False                 False                 False
11                 False                 False                 False
12                 False                 False                 False
13                  True                  True                 False
14                 False                 False                 False
15                 False                 False                 False
16                 False                 False                 False
17                 False                 False                 False
18                 False                 False                 False
19                  True                 False                 False

    week6_variance_contr  week7_variance_contr  week8_variance_contr  \
0                  False                 False                 False
1                  False                 False                 False
2                  False                 False                 False
3                  False                 False                 False
4                  False                 False                 False
5                  False                 False                 False
6                  False                 False                 False
7                  False                 False                 False
8                  False                 False                 False
9                  False                 False                 False
10                 False                 False                 False
11                 False                 False                 False
12                 False                 False                 False
13                 False                 False                 False
14                 False                 False                 False
15                 False                 False                 False
16                 False                 False                 False
17                 False                 False                 False
18                  True                 False                 False
19                 False                 False                 False

    week9_variance_contr  week10_variance_contr  week11_variance_contr
0                  False                  False                  False
1                  False                  False                  False
2                  False                  False                  False
3                  False                  False                  False
4                  False                  False                  False
5                  False                  False                  False
6                  False                  False                  False
7                  False                  False                  False
8                  False                  False                  False
9                  False                  False                  False
10                 False                  False                  False
11                 False                  False                  False
12                 False                  False                  False
13                 False                  False                  False
14                 False                  False                  False
15                 False                  False                  False
16                 False                  False                  False
17                 False                  False                  False
18                 False                  False                  False
19                 False                  False                  False